/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Fri Jul 22 19:06:45 2022 */

/* parameterized module instance */
clk_pll __ (.CLKI( ), .CLKOP( ));
