/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.4 */
/* Mon Jul 25 17:56:30 2022 */

/* parameterized module instance */
sin_rom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
